spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: postgres
    password: Chemege1.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    net.az3l1t.game_server.service.impl.RecordService: INFO
server:
  port: 8025
