spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: alphabet
          uri: http://localhost:8020
          predicates:
            - Path=/**
        - id: game
          uri: http://localhost:8025
          predicates:
            - Path=/**
        - id: news
          uri: http://localhost:8015
          predicates:
            - Path=/**
        - id: security
          uri: http://localhost:8005
          predicates:
            - Path=/**
        - id: words
          uri: http://localhost:8030
          predicates:
            - Path=/words/**
server:
  port: 8000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true